include: package:very_good_analysis/analysis_options.3.1.0.yaml
analyzer:
  plugins:
    - custom_lint
  exclude:
    - build/**
    - /**/*.g.dart
    - /**/*.freezed.dart
    - /**/*.config.dart
    - /**/l10n.dart
    - /**/generated/**
    - /**/firebase_options*.dart
linter:
  rules:
    public_member_api_docs: false